export default function getAuthorizationHeaderWithJWT() {
    return "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRob3JpdGllcyI6IlJPTEVfVVNFUiIsInVzZXJuYW1lIjoiZGljdGF0b3JfengifQ.Jz2twRUHJP4EIYnOeqxWsU83w89UhyWBqZ9ZrIG58co"
}